name: Portfolio CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: Check HTML
        run: echo "HTML checked"

      - name: Check CSS
        run: echo "CSS checked"

      - name: Check JavaScript
        run: echo "JS checked"

      - name: Build Success
        run: echo "Portfolio Passed"